### ISSUE TITLE
Job version to handle code updates

### ISSUE THREAD

**Issue by nclavaud** [schmittjoh/JMSJobQueueBundle#111]
We have been using this bundle for a while now and we are now looking for a smart way to handle code updates without having to worry about the job runner currently running.

Each time we deploy new code, we must make sure the job runner (running old code) won't fail processing new jobs, otherwise we have to wait for the runner to shutdown before doing the update. See https://github.com/schmittjoh/JMSJobQueueBundle/issues/83 and https://github.com/schmittjoh/JMSJobQueueBundle/issues/90. This deployment process is cumbersome and painful for our team.

Right now we're thinking about implementing job versions:
  * when the job runner is started, it should know the current code version (e.g. `2.0.0`) ;
  * when a job is scheduled, persist the current code version (e.g. `2.0.1`) ;
  * when the job runner starts a job, skip if versions don't match (`job 2.0.1 > runner 2.0.0`).

This way, an old job runner won't fail trying to start new jobs. Those jobs will be processed as soon as a new job runner is restarted.

What do you think?

**Comment by Blackskyliner** [comment]
Sounds reasonable but what about the following edge case:

- Runner running v2.0.0 (100 Jobs in queue)
- Update to v3.0.0
- Runner running v2.0.0 dies because of timelimit (10 Jobs left in queue)
- Now an v3.0.0 Runner fires up but he can't handle v2.0.0 Jobs anymore, because the feature got deprecated and replaced with new fancy, shiny stuff.

It could ignore everything with Major changes (e.G. v2.X Jobs) but what about them? Delete them? What if they generated Invoices and the new proccess can't regenerate the data needed for a v3.x Invoice because of missing data, which was introduced in the 3.x release?

I know you could use transitions/migrations or could lock the whole proccess before updating, thus having not to worry about it on major updates. But its en edgy edgecase :smile: I know its a bit constructed, but one may find a more appropriate example/edgecase if trying hard enough, I guess.

**Comment by schmittjoh** [comment]
How long are your jobs running?

**Comment by schmittjoh** [comment]
I think you'll need to handle this in your application. Preferably making a backwards compatible migrations. Where the V3 job can handle V3 jobs and also V2 jobs.
