### ISSUE TITLE
JobQueue aware commands

### ISSUE THREAD

**Issue by tobiassjosten** [schmittjoh/JMSJobQueueBundle#5]
It seems the command you want to queue [needs to be JobsQueue aware](https://github.com/schmittjoh/JMSJobQueueBundle/blob/ad0292c410e07954a79b97db7c03065cbd944d0c/Command/RunCommand.php#L203)?

Would you recommend setting up "wrapper commands" to run the ones I actually want executed? Or is there a way to have JobQueueBundle run my commands without adding the `--jms-job-id` option to them all?

**Comment by Aerendir** [comment]
This is really an ugly requirement! Also because currently the `console` class is really different from the one provided by the bundle. Also the maintenance is an hell.

Why not using a `trait`? They were introduced in PHP 5.4 and the bundle requires at least PHP 5.5, so they are for sure supported...

I can work on it as I'm really not willing to edit in a so strong way my `console` file.
